---
# ***********************************************
# Install Java
# ***********************************************

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: java

- name: Install Java 25 headless (OpenJDK)
  ansible.builtin.apt:
    name: openjdk-25-jre-headless
    state: present
  tags: java

- name: Verify Java is available
  ansible.builtin.command: java -version
  changed_when: false
  tags: java

# ***********************************************
# Create a dedicated system user
# ***********************************************

- name: Create minecraft group
  ansible.builtin.group:
    name: "{{ minecraft_group }}"
    system: true
    state: present

- name: Create minecraft user
  ansible.builtin.user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    home: "{{ minecraft_dir }}"
    shell: /usr/sbin/nologin   # no interactive login as to practice principle of least privilege
    system: true
    create_home: false
    state: present

# ***********************************************
# Set up server directory
# ***********************************************

- name: Create Minecraft server directory
  ansible.builtin.file:
    path: "{{ minecraft_dir }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0755"

# ***********************************************
# Download the Minecraft server JAR
# ***********************************************

- name: Download Minecraft server JAR ({{ minecraft_version }})
  ansible.builtin.get_url:
    url: "{{ minecraft_jar_url }}"
    dest: "{{ minecraft_dir }}/server.jar"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  tags: download

# ***********************************************
# Accept the EULA
# ***********************************************

- name: Accept Minecraft EULA
  ansible.builtin.copy:
    dest: "{{ minecraft_dir }}/eula.txt"
    content: "eula=true\n"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  tags: eula

# ***********************************************
# Write server.properties to restart server
# ***********************************************

- name: Write server.properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: "{{ minecraft_dir }}/server.properties"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: "0644"
  tags: config

